<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-UICENVRK" failures="1" tests="1" name="Test" time="25.573" errors="0" timestamp="06 Aug 2024 06:29:21 GMT">
  <testcase classname="TestComponents.OrderProduct" name="TestCase001" time="17.252">
    <failure type="java.lang.AssertionError" message="expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [1]
at PageObjects.CheckOutPage.quantityCheck(CheckOutPage.java:48)
at TestComponents.OrderProduct.TestCase001(OrderProduct.java:28)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TestCase001 -->
</testsuite> <!-- Test -->
